### ISSUE TITLE
How to use the method on a custom dataset?

### ISSUE THREAD

**Issue by bakachan19** [pietrobarbiero/pytorch_explain#7]
Hi. thanks for such an interesting work.
I was wondering if your method can be applied to a custom image dataset.
I've seen that in the paper "Concept Embedding Models: Beyond the Accuracy-Explainability Trade-Off" you also did experiments on CUB dataset but I could not find the associated code.

Can you please provide the code for the CUB dataset or give some instructions on how to prepare a custom dataset of images in order to apply your method?

Thank you.
Best wishes.

**Comment by mateoespinosa** [comment]
Hey @bakachan19! Thanks for opening this ticket! For some useful examples, please refer to [this example](https://github.com/pietrobarbiero/pytorch_explain#quick-tutorial-on-concept-embedding-models) on using a CEM or  [this notebook](https://github.com/mateoespinosa/cem/blob/main/examples/dot_cem_train_walkthrough.ipynb) on the official CEM repository. If you have any issues with those examples and/or code, please reopen this ticket and let us know how we can help. Happy coding and researching!

**Comment by bakachan19** [comment]
Dear @mateoespinosa,
Thank you for your help.
I will give it a try and let you know if I need additional information/help.
Have a great day!
